-- CREATE TABLE `boards` (
--   `id` int NOT NULL AUTO_INCREMENT,
--   `player1` varchar(36) NOT NULL,
--   `player2` varchar(36) NOT NULL,
--   `player3` varchar(36) DEFAULT NULL,
--   `player4` varchar(36) DEFAULT NULL,
--   `creator` varchar(36) NOT NULL,
--   `creationMode` enum('manual','system') DEFAULT NULL,
--   `startTime` datetime DEFAULT CURRENT_TIMESTAMP,
--   `endTime` datetime DEFAULT NULL,
--   `status` enum('active','suspended','finished') DEFAULT NULL,
--   `winner1` varchar(36) DEFAULT NULL,
--   `winner2` varchar(36) DEFAULT NULL,
--   `winner3` varchar(36) DEFAULT NULL,
--   `loser` varchar(36) DEFAULT NULL,
--   `numberOfPawnsUnlocked` int DEFAULT NULL,
--   `endTime` datetime(3) DEFAULT CURRENT_TIMESTAMP(3),
--   PRIMARY KEY (`id`),
--   KEY `player1` (`player1`),
--   KEY `player2` (`player2`),
--   KEY `player3` (`player3`),
--   KEY `player4` (`player4`),
--   KEY `creator` (`creator`),
--   KEY `winner1` (`winner1`),
--   KEY `winner2` (`winner2`),
--   KEY `winner3` (`winner3`),
--   KEY `loser` (`loser`),
--   CONSTRAINT `boards_ibfk_1` FOREIGN KEY (`player1`) REFERENCES `flms` (`flmId`),
--   CONSTRAINT `boards_ibfk_2` FOREIGN KEY (`player2`) REFERENCES `flms` (`flmId`),
--   CONSTRAINT `boards_ibfk_3` FOREIGN KEY (`player3`) REFERENCES `flms` (`flmId`),
--   CONSTRAINT `boards_ibfk_4` FOREIGN KEY (`player4`) REFERENCES `flms` (`flmId`),
--   CONSTRAINT `boards_ibfk_5` FOREIGN KEY (`creator`) REFERENCES `admins` (`adminId`),
--   CONSTRAINT `boards_ibfk_6` FOREIGN KEY (`winner1`) REFERENCES `flms` (`flmId`),
--   CONSTRAINT `boards_ibfk_7` FOREIGN KEY (`winner2`) REFERENCES `flms` (`flmId`),
--   CONSTRAINT `boards_ibfk_8` FOREIGN KEY (`winner3`) REFERENCES `flms` (`flmId`),
--   CONSTRAINT `boards_ibfk_9` FOREIGN KEY (`loser`) REFERENCES `flms` (`flmId`)
-- ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci



CREATE TABLE `boards` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `player1` varchar(36) NOT NULL,
  `player2` varchar(36) NOT NULL,
  `player3` varchar(36) DEFAULT NULL,
  `player4` varchar(36) DEFAULT NULL,
  `creator` varchar(36) NOT NULL,
  `creationMode` enum('manual','system','excel') DEFAULT NULL,
  `startTime` datetime(3) DEFAULT CURRENT_TIMESTAMP(3),
  `endTime` datetime(3) DEFAULT CURRENT_TIMESTAMP(3),
  `status` enum('active','finished','noResult','upcoming','suspended') NOT NULL,
  `winner1` varchar(36) DEFAULT NULL,
  `winner2` varchar(36) DEFAULT NULL,
  `winner3` varchar(36) DEFAULT NULL,
  `loser` varchar(36) DEFAULT NULL,
  `numberOfPawnsUnlocked` int DEFAULT NULL,
  `actualEndTime` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `player1` (`player1`),
  KEY `player2` (`player2`),
  KEY `player3` (`player3`),
  KEY `player4` (`player4`),
  KEY `creator` (`creator`),
  KEY `winner1` (`winner1`),
  KEY `winner2` (`winner2`),
  KEY `winner3` (`winner3`),
  KEY `loser` (`loser`),
  CONSTRAINT `boards_ibfk_1` FOREIGN KEY (`player1`) REFERENCES `flms` (`flmId`),
  CONSTRAINT `boards_ibfk_2` FOREIGN KEY (`player2`) REFERENCES `flms` (`flmId`),
  CONSTRAINT `boards_ibfk_3` FOREIGN KEY (`player3`) REFERENCES `flms` (`flmId`),
  CONSTRAINT `boards_ibfk_4` FOREIGN KEY (`player4`) REFERENCES `flms` (`flmId`),
  CONSTRAINT `boards_ibfk_5` FOREIGN KEY (`creator`) REFERENCES `admins` (`adminId`),
  CONSTRAINT `boards_ibfk_6` FOREIGN KEY (`winner1`) REFERENCES `flms` (`flmId`),
  CONSTRAINT `boards_ibfk_7` FOREIGN KEY (`winner2`) REFERENCES `flms` (`flmId`),
  CONSTRAINT `boards_ibfk_8` FOREIGN KEY (`winner3`) REFERENCES `flms` (`flmId`),
  CONSTRAINT `boards_ibfk_9` FOREIGN KEY (`loser`) REFERENCES `flms` (`flmId`)
) ENGINE=InnoDB AUTO_INCREMENT=181 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci