CREATE TABLE `flms` (
  `id` varchar(36) NOT NULL DEFAULT (uuid()),
  `flmId` varchar(255) NOT NULL,
  `flmName` varchar(255) DEFAULT NULL,
  `password` varchar(255) DEFAULT NULL,
  `hq` varchar(255) DEFAULT NULL,
  `zone` varchar(255) DEFAULT NULL,
  `teamName` varchar(255) DEFAULT NULL,
  `points` int DEFAULT '0',
  `kills` int DEFAULT '0',
  `hearts` int DEFAULT '0',
    `diamonds` int DEFAULT '0',
  `status` varchar(255) DEFAULT 'Active',
  `createdAt` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `slmId` varchar(255) DEFAULT NULL,
  `region` varchar(255) DEFAULT NULL,
  `diceRolled` int DEFAULT '0',
  `mrCount` int DEFAULT '0',
  `currentDiceRollBalance` int DEFAULT '0',
  `moves` int DEFAULT '0',
  `currentMoveBalance` int DEFAULT '0',
  `adminId` varchar(36) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `flmId` (`flmId`),
  KEY `fk_flm_slm` (`slmId`),
  CONSTRAINT `fk_flm_slm` FOREIGN KEY (`slmId`) REFERENCES `slms` (`slmId`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci


-- CREATE TABLE `flms` (
--   `id` varchar(36) NOT NULL DEFAULT (uuid()),
--   `flmId` varchar(255) NOT NULL,
--   `flmName` varchar(255) DEFAULT NULL,
--   `password` varchar(255) DEFAULT NULL,
--   `hq` varchar(255) DEFAULT NULL,
--   `zone` varchar(255) DEFAULT NULL,
--   `kills` int DEFAULT NULL,
--   `diamonds` int DEFAULT '0',
--   `status` varchar(255) DEFAULT 'Active',
--   `createdAt` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
--   `updatedAt` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
--   `slmId` varchar(255) DEFAULT NULL,
--   `region` varchar(255) DEFAULT NULL,
--   `points` int DEFAULT '0',
--   `moves` int DEFAULT '200',
--   `currentBalanceMoves` int DEFAULT '200',
--   `mrCount` int DEFAULT '0',
--   PRIMARY KEY (`id`),
--   UNIQUE KEY `flmId` (`flmId`),
--   KEY `fk_flm_slm` (`slmId`),
--   CONSTRAINT `fk_flm_slm` FOREIGN KEY (`slmId`) REFERENCES `slms` (`slmId`) ON DELETE CASCADE ON UPDATE CASCADE
-- ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci