CREATE TABLE `mrs` (
  `id` varchar(36) NOT NULL DEFAULT (uuid()),
  `mrId` varchar(255) NOT NULL,
  `mrName` varchar(255) DEFAULT NULL,
  `password` varchar(255) DEFAULT NULL,
  `hq` varchar(255) DEFAULT NULL,
  `zone` varchar(255) DEFAULT NULL,
  `teamName` varchar(255) DEFAULT NULL,
  `points` int DEFAULT '0',
  `diceRollBalance` int DEFAULT '0',
  `hasAccess` tinyint(1) DEFAULT '0',
  `fromDate` datetime DEFAULT NULL,
  `toDate` datetime DEFAULT NULL,
  `status` varchar(255) DEFAULT 'Active',
  `createdAt` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `flmId` varchar(255) DEFAULT NULL,
  `email` varchar(255) DEFAULT NULL,
  `role` varchar(100) DEFAULT NULL,
  `region` varchar(255) DEFAULT NULL,
  `businessUnit` varchar(255) DEFAULT NULL,
  `dateOfJoining` varchar(255) DEFAULT NULL,
  `adminId` varchar(36) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `mrId` (`mrId`),
  KEY `fk_mr_flm` (`flmId`),
  CONSTRAINT `fk_mr_flm` FOREIGN KEY (`flmId`) REFERENCES `flms` (`flmId`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci