CREATE TABLE `prescriptions` (
  `id` varchar(36) NOT NULL DEFAULT (uuid()),
  `mrId` varchar(255) NOT NULL,
  `brandId` varchar(36) NOT NULL,
  `brandName` varchar(255) NOT NULL,
  `drName` varchar(255) DEFAULT NULL,
  `speciality` varchar(255) DEFAULT NULL,
  `mobNo` varchar(20) DEFAULT NULL,
  `scCode` varchar(255) DEFAULT NULL,
  `noRxns` int NOT NULL DEFAULT 1,
  `rxnDuration` int DEFAULT 1,
  `prescriptionImage` varchar(500) DEFAULT NULL,
  `dateOfUpload` date NOT NULL,
  `timeOfUpload` time DEFAULT NULL,
  `points` int DEFAULT 0,
  `isCalculated` tinyint(1) DEFAULT 0,
--   `status` enum('pending','approved','rejected') DEFAULT 'pending',
--   `reason` text DEFAULT NULL,
--   `modifiedDate` datetime DEFAULT NULL,
  `createdAt` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `fk_prescription_mr` (`mrId`),
  KEY `fk_prescription_brand` (`brandId`),
  KEY `idx_dateOfUpload` (`dateOfUpload`),
--   KEY `idx_status` (`status`),
  CONSTRAINT `fk_prescription_mr` FOREIGN KEY (`mrId`) REFERENCES `mrs` (`mrId`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_prescription_brand` FOREIGN KEY (`brandId`) REFERENCES `brands` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

